# Generated by Django 4.2.6 on 2023-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ONX', 'OnyxBoox'), ('PB', 'PocketBooks')], max_length=20),
        ),
    ]
