# Generated by Django 4.2.6 on 2023-11-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
