name: GitHub Actions
on:
  push:
    paths:
      - 'client/**'
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: unit test
        run: yarn test
      - name: format code
        run:  yarn formatj
      - name: lint code
        run: yarn lint
